### ISSUE TITLE
pyVRS roadmap

### ISSUE THREAD

**Issue by openmoverse** [facebookresearch/vrs#117]
Hello everyone,
as we've noticed, you're moving the whole pyvrs wrapper to whole another project.
Can you give a rough estimate on the roadmap and when we'll be able to see that working?
Will it support Windows platform, since we've been working with vrs on our Windows machines 
for a while now ( PR can be found [here](https://github.com/facebookresearch/vrs/pull/116) )

Best regards

**Comment by kiminoue7** [comment]
Hi @openmoverse, we moved pyvrs to its own repo to streamline the pypi package build. We could confirm that the build works for manylinux as well and currently working on documentation clean ups + preparing for the internal review to make it public.
Task-wise this is almost ready but when we can make it public it depends on how smooth internal review goes. We are looking for 1-2 weeks but might take a little more. Sorry for the inconvenience.

I'll update the pyvrs section shortly to reflect this information

**Comment by openmoverse** [comment]
Thank you, closing this.
