### ISSUE TITLE
pip installation of vrs does not come with command line tool

### ISSUE THREAD

**Issue by Davidyao99** [facebookresearch/vrs#132]
I am trying to work with vrs files on the aria data tools. I am unable to find the vrs binary for the vrs command line tools after downloading it from pip. Am I doing something wrong? Thanks!

**Comment by georges-berenger** [comment]
The vrs binary comes from the vrs project, not pyvrs or aria, and has no business being part of pyvrs and pip. Aria data tools might want to expose it for convenience, but pyvrs/pip is not the place.
@kiminoue7 @SeaOtocinclus what do you think?

**Comment by kiminoue7** [comment]
I agree with @georges-berenger about vrs CLI not being part of pyvrs.
vrs CLI is pure C++ library and I don't think it's right to silently install it when the user installs pyvrs unless it's always used together.

**Comment by kiminoue7** [comment]
@Davidyao99 if you want to use vrs binary please build it with cmake.
If you have further suggestions or questions please let us know.

**Comment by ddetone** [comment]
@georges-berenger are there instructions somewhere on how to build the `vrs` binary tool with cmake? Maybe we can add them to the README if not?

**Comment by georges-berenger** [comment]
It's part of the cmake targets of the vrs project. Use the instructions at https://github.com/facebookresearch/vrs, go to the build folder, build everything if that's not done already (run `ninja`), or just build the cmd line tool with `ninja vrs`, then run `./oss/tools/vrs/vrs`.
