### ISSUE TITLE
VRS image/video support

### ISSUE THREAD

**Issue by moversevlad** [facebookresearch/vrs#136]
As far as you've made public, no video support is present yet.
Is there any plans for it? Especially h264?

**Comment by georges-berenger** [comment]
Correct, no public support for video codec compression at this point. What we have requires a slightly modified version of ffmpeg to be able to reliably handle single frame compression, and that's a pain in the butt to publish/officialize, and we don't have bandwidth for that (on top of dealing with ffmpeg).
