### ISSUE TITLE
setGlobalLogLevel does not work

### ISSUE THREAD

**Issue by chpeng-fb** [facebookresearch/vrs#139]
When setting in the main function `arvr::logging::setGloablLogLevel(arvr::logging::level::Info)`, the output is unchanged where all level of log with`XR_LOG` is outputing information. Ideally, setting different log levels should be able to filter out certain levels.

**Comment by georges-berenger** [comment]
The OSS default implementation of logging is primitive indeed. If you want to do something better in OSS, you're welcome to make a contribution, but for now, this is the open source MVP.
