### ISSUE TITLE
Issue with rapidjson when building

### ISSUE THREAD

**Issue by jmpfar** [facebookresearch/vrs#147]
Hi, really nice library! ☄️

When building the project I got the following error from cmake:

```
fatal: could not create work tree dir '/rapidjson': Read-only file system
/usr/bin/cd: line 4: cd: /rapidjson: No such file or directory
CMake Error at /usr/local/lib/cmake/vrslib/cmake/FindRapidjsonLib.cmake:33 (message):
  Could not setup rapidjson external dependency at /rapidjson
Call Stack (most recent call first):
  /usr/local/lib/cmake/vrslib/cmake/LibrariesSetup.cmake:29 (find_package)
  /usr/local/lib/cmake/vrslib/vrslibConfig.cmake:45 (include)
  /Users/x/.../CMakeLists.txt:20 (find_package)
```

After reading a bit of the cmake code and the python library I realized what was missing is the following line:
```
set(EXTERNAL_DEPENDENCIES_DIR "${CMAKE_BINARY_DIR}/external")
```

It looks like it is either something specific to my environment (MacOS) or something missing from the docs. Also currently the make files triggers a git clone on clean build, it'd be nice if that could be changed as it slows down builds and adds a networking dependency 🙏

**Comment by georges-berenger** [comment]
`EXTERNAL_DEPENDENCIES_DIR` should always end up being set by [this code](https://github.com/facebookresearch/vrs/blob/5f86e0daff7926163a949066d1dd18b32ff7d258/CMakeLists.txt#L331) , which is at the top of the cmake code. I'm not sure how it's not set for you, but you need to make sure to include that top cmake file, that's a requirement. The other cmake lists should not be accessed directly.

**Comment by jmpfar** [comment]
Hey, thanks for the reply!
So my flow was as mentioned [here](https://github.com/facebookresearch/vrs?tab=readme-ov-file#build--run-macos--linux):

I compiled and installed the library locally, I then added `find_package(vrslib REQUIRED)` to my cmake file. That line failed with the above mentioned error. So reading your response, do you think I should have imported that `CMakeLists.txt` file manually because for some reason it wasn't included on its own?

**Comment by georges-berenger** [comment]
The code I pointed to sets `EXTERNAL_DEPENDENCIES_DIR` if it's not set externally, which is an optional customization option given to the users of the library. You need to debug why it's not happening for you, because you should not get to the `FindRapidjsonLib.cmake` file without going through that code first.
I'm not sure I understand your question. The only `CMakeLists.txt` in the vrs project you should use directly is the top one, in the main folder.

**Comment by jmpfar** [comment]
Alright, I wasn't aware that cmake is supposed to import a library's `CMakeLists.txt` in `find_package` but I only recently started working with it so that makes perfect sense. If that's the case then this sounds like this is an issue in my specific environment

Feel free to close, in any case it might be helpful to anyone seeing the same error
