### ISSUE TITLE
support decoding in javascript (?)

### ISSUE THREAD

**Issue by breathe** [facebookresearch/vrs#158]
---

## 🚀 Feature

Would be quite cool to be able to decode this file type from javascript

## Motivation & Examples

Would be very nice to consume vrs file directly from browser apps.  That would add a nice benefit which would make it easier to justify adoption of vrs.

**Comment by georges-berenger** [comment]
Thanks for the feedback. VRS is too complex to justify such an effort, that would require lots of maintenance overhead, too. We've seen some results with wasm, though there were a number of hacks involved, but that seems like a more realistic approach that doesn't require a separate implementation.
We have Meta-internal solutions for web playback, but they involve lots of code that can't be open sourced, unfortunately.
