### ISSUE TITLE
Cmake configuration error when using Ubuntu 22.04

### ISSUE THREAD

**Issue by paulsammut** [facebookresearch/vrs#53]
Hello, I'm trying to get this VRS library to build using a docker container with the following Ubuntu image:

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
```

When I try to run the following cmake configuration I get an error about a non-existant path in `cereal::cereal`:
```
cmake -DCMAKE_BUILD_TYPE=RELEASE /opt/vrs '-GCodeBlocks - Ninja'
-- CMAKE_CXX_COMPILER: /usr/bin/c++
-- CMAKE_CXX_COMPILER_VERSION: 11.2.0
-- CCACHE enabled
-- Configuring done
CMake Error in vrs/helpers/CMakeLists.txt:
  Imported target "cereal::cereal" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in vrs/helpers/CMakeLists.txt:
  Imported target "cereal::cereal" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in vrs/helpers/CMakeLists.txt:
  Imported target "cereal::cereal" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

I installed `libcereal-dev` along with all the other dependencies. This issue does not come up when using an Ubuntu 20.04 version.

Any help would be greatly appreciated :)

**Comment by georges-berenger** [comment]
:( We don't have a 22.04 setup ready to play with, so we need to find time to understand why 22.04 doesn't behave like the same as 20.04 that we're currently using for CI. Since 22.04 is an LTS release, we need to support it.

**Comment by mborows2** [comment]
Ubuntu 22.04 libcereal-dev package include cmake files, 20.04 package version does not. VRS  tries to use find_package(cereal QUIET CONFIG) first and in case of 22.04 (it use /usr/share/cmake/cereal/cerealTargets.cmake)  set include path incorrectly). You can simply comment out line15 in vrs/cmake/FindCereal.cmake and have similar behavior like in 20.04. This solve that problem, but you will probably had another one related to fb_rapidjson namespace.

**Comment by fnoriegaz** [comment]
Maybe the issue was already solved since it  was reported one year ago. 
I was also getting the same problem recently and instead of installing the dependency like `apt-get install libcereal-dev` I came out that it works better by fetching the latest version, source code, of cereal within my dockerfile like:

```dockerfile
RUN wget --no-check-certificate https://github.com/USCiLab/cereal/archive/refs/heads/master.zip \
    && unzip master.zip \
    && cd cereal-master \
    && mkdir build \
    && cd build \
    && cmake -Wno-dev .. \
    && make -j12\
    && make install \
    && cd ../../ \
    && rm -rf master.zip
``` 
And then of course cloning or running wget to install vrs itself.

**Comment by georges-berenger** [comment]
We have now removed the dependency on cereal, which was causing this issue.
