### ISSUE TITLE
Amendments to README.md.

### ISSUE THREAD

**Issue by FalFlower** [facebookresearch/vrs#91]
---

## 🚀 Feature

After our tests,only in ubuntu 20.04 and later to compile the code correctly. So we recommend adding a minimum system version support in REAME.md.

## Motivation & Examples

Since many people have a system version of 18.04, specifying the minimum system version will save a lot of time!!!

**Comment by georges-berenger** [comment]
fair enough, I'll do that.

**Comment by georges-berenger** [comment]
Note: It is already implied pretty heavily that Ubuntu 18.04 won't work in this section:
https://github.com/facebookresearch/vrs#install-build-tools--libraries-ubuntu
