### ISSUE TITLE
Clarification about appropriate use cases

### ISSUE THREAD

**Issue by andre-nguyen** [facebookresearch/vrs#97]
Hi,

the documentation mentions that "point cloud data" is a poor use case however it seems to me that it fits the criteria of having data regularity and time stamps (when coming from a lidar). 

Is recording data from a lidar a poor use case or does the documentation mean specifically point cloud environment models, e.g. after post processing and assembling from a scanner?

Thanks,

**Comment by georges-berenger** [comment]
Good point. If you have point cloud data updated at different points in time, it would be a proper use case for VRS, just as using VRS to save one image makes no sense, but using VRS to save images produced at different points in time does make sense.
